[tox]
envlist = py310, lint, typecheck
skipsdist = True

[testenv]
deps =
    -r requirements.txt
    pytest
    pytest-cov
commands =
    pytest --cov=pneumonia_classifier --cov-report=term-missing tests/

[testenv:lint]
deps =
    flake8
    black
commands =
    flake8 pneumonia_classifier tests frontend
    black --check pneumonia_classifier tests frontend

[testenv:typecheck]
deps =
    mypy
    -r requirements.txt
commands =
    mypy pneumonia_classifier
