import os
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


class ReportGenerator:
    @staticmethod
    def generate_clinical_report(patient_id, prediction, confidence, heatmap_base64, original_image_base64, output_path):
        """
        Generates a professional clinical PDF report.
        """
        temp_heatmap_path = "temp_heatmap_final.png"
        temp_orig_path = "temp_orig_final.png"
        c = canvas.Canvas(output_path, pagesize=letter)
        width, height = letter

        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width/2, height - 50, "PnuemoCheck AI: Clinical Diagnostic Report")

        c.setStrokeColorRGB(0.7, 0.7, 0.7)
        c.line(50, height - 70, width - 50, height - 70)

        # Patient Info
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, height - 100, f"Patient ID: {patient_id}")
        c.drawString(50, height - 120, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        # Results
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 160, "Diagnostic Results:")

        c.setFont("Helvetica", 12)
        result_color = (0.8, 0.2, 0.2) if prediction.upper() == "PNEUMONIA" else (0.2, 0.6, 0.2)
        c.setFillColorRGB(*result_color)
        c.drawString(70, height - 180, f"System Prediction: {prediction.upper()}")

        c.setFillColorRGB(0, 0, 0)
        c.drawString(70, height - 200, "Architecture: Tri-Modal Ensemble (CNN + EfficientNet + ViT)")
        c.drawString(70, height - 220, f"Confidence Level: {confidence}")

        # Images (Original and Heatmap)
        import base64
        import io

        from PIL import Image

        def draw_b64_image(b64_str, path, x, y, label):
            try:
                if b64_str and "," in b64_str:
                    _, encoded = b64_str.split(",", 1)
                    data = base64.b64decode(encoded)
                    img = Image.open(io.BytesIO(data))
                    img.save(path)
                    c.drawImage(path, x, y, width=240, height=200, preserveAspectRatio=True)
                    c.setFont("Helvetica-Bold", 10)
                    c.drawString(x, y - 15, label)
                    return True
            except Exception:
                pass
            return False

        # Positions for side-by-side images
        img_y = height - 450

        # 1. Original Image
        draw_b64_image(original_image_base64, temp_orig_path, 50, img_y, "Original X-ray Scan")

        # 2. Heatmap (Pneumonia only)
        if prediction.upper() == "PNEUMONIA":
            draw_b64_image(heatmap_base64, temp_heatmap_path, 310, img_y, "AI Focus Analysis (Grad-CAM)")

        # Footer
        c.line(50, 50, width - 50, 50)
        c.setFont("Helvetica", 8)
        c.drawCentredString(width/2, 35, "Confidential Medical Documentation - Generated by PnuemoCheck AI System")

        c.save()

        # Cleanup
        for p in [temp_heatmap_path, temp_orig_path]:
            if os.path.exists(p):
                os.remove(p)

        return output_path
